### ISSUE TITLE
Bringing up IP does not always succeed, failing with NameError: name 'ip_addr' is not defined

### ISSUE THREAD

**Issue by strife242** [xmm7360/xmm7360-pci#5] opened 2020-01-08 22:36 UTC
Hello,

First I as the others also would like to thank for the awesome work. I just decided to check into the mobile broadband support again today, and found this.

It loads fine, when trying to run the "open_xdatachannel.py" however I get the following trace.
The interface is created and I get a link-local IPv6 address but nothing else. This may be related to the SIM card as I don't know the status of it so I will try again with a new card tomorrow. Meanwhile, if the SIM is not the issue maybe you find the trace useful anyway.

(IPv4Address('0.0.0.0'), IPv4Address('0.0.0.0'), IPv4Address('0.0.0.0'))
{'v4': [], 'v6': []}
Traceback (most recent call last):
  File "rpc/open_xdatachannel.py", line 47, in <module>
    address=ip_addr)
NameError: name 'ip_addr' is not defined

**Comment by strife242** [comment] 2020-01-09 20:13
Hello again. Just wanted to confirm, with a fresh SIM card and active data plan this works (almost) like a charm. The error message in the original post can happen still, but after running open_xdatachannel.py a few more times it succeeds in taking the interface up and retrieving an IP-address.

Specs on computer is:
HP ZBook 14u G5
Kubuntu 18.10, Linux version 4.18.0-25-generic

One note though, you may have to add DNS-servers manually as they seem not to be retrieved automatically.

Once again, awesome work!

**Comment by abrasive** [comment] 2020-01-10 14:19
This race is the same as #7 and #9, which is probably executing commands before the modem is ready.
We should be waiting for certain unsolicited events before proceeding with certain commands, but I don't know which are the important ones. I can't reproduce this problem here, so can somebody with the issue perhaps figure it out?

I have dug the unsolicited event names out of the firmware and updated the rpc code to print everything nicelier. You should now be able to see which functions are failing (they will return codes like 0xffffff78 instead of 0x0) as well as the meaning and timing of the indications.

If someone wants to just throw down a log of it failing, and a log of it succeeding, then we can probably work it out. Note that this might contain personal information? I don't see an IMEI or anything but I can't be sure.

**Comment by e-aranda** [comment] 2020-01-10 15:37
I attach the result of python3 /rpc/open_xdatachannel.py
[result.log](https://github.com/xmm7360/xmm7360-pci/files/4046388/result.log)

**Comment by abrasive** [comment] 2020-01-11 00:19
Thanks. Pushed a possible fix, does it work for you?
This now waits until it's allowed to do the attach before proceeding to do so.

**Comment by e-aranda** [comment] 2020-01-11 09:31
Sorry I have not understood your last sentence. 

First time executing /rpc/open_xdatachannel.py there is no error, but it "hangs"? After waiting a while I have interrupted. The result was:
[newresul.log](https://github.com/xmm7360/xmm7360-pci/files/4049148/newresul.log)

Then, I have tried again and now is saying

    Attach failed - waiting to see if we just weren't ready

**Comment by e-aranda** [comment] 2020-01-11 09:52
The interface wwan0 has not been created, and while /rpc/open_xdatachannel.py is running I tried another instance of /rpc/open_xdatachannel.py, I get

    Traceback (most recent call last):
      File "rpc/open_xdatachannel.py", line 9, in <module>
        r = rpc.XMMRPC()
      File "/home/earanda/xmm7360-pci/rpc/rpc.py", line 18, in __init__
        self.fp = os.open(path, os.O_RDWR | os.O_SYNC)
    OSError: [Errno 16] Device or resource busy: '/dev/xmm0/rpc'

**Comment by abrasive** [comment] 2020-01-11 10:45
@e-aranda Does your SIM need a PIN? You can try using `AT+CPIN` via `/dev/ttyXMM1` if it does.

**Comment by e-aranda** [comment] 2020-01-11 11:15
I hace disabled PIN in my SIM. I think my APN needs a user and password, however I don't need to introduce un Windows, nor the APM.

**Comment by abrasive** [comment] 2020-01-11 12:09
@e-aranda You definitely need to set the APN at least here, this driver doesn't know how to ask the SIM for the default details to use. If I read the log right, you're with Movistar? So in `open_xdatachannel.py`, replace `telstra.internet` with `telefonica.es` or whatever, and try again.

**Comment by e-aranda** [comment] 2020-01-11 15:20
Yes, I replace `telstra.internet` with `movistar.es` but the result is the same. In this page 

https://www.dell.com/support/article/es/es/esbsdt1/sln60881/3g-mobile-broadband-modem-how-to-configure-and-use-3g-on-a-dell-pc-using-the-ubuntu-operating-system?lang=en

there is a list of internet providers and it says that `telstra` does not need user and password but need to dial `*99#`, while `movistar.es` does not need dialing but use user and password.

I am sorry, I am completely new about these things and don't know what to try, but if you need to check anything, just say it.

**Comment by woopstar** [comment] 2020-03-02 13:36
Fixed by #26

**Comment by massimoruoroch** [comment] 2021-01-25 08:29
Fix works on Lenovo T15

**Closed** 2021-03-10 06:05 UTC
Labels: mysteries

**Comment by tgxn** [comment] 2021-03-10 06:07
#26 has been merged, hopeful; for fix, otherwise please open new issue :)
