### ISSUE TITLE
Supplying APN credentials 

### ISSUE THREAD

**Issue by elronzo** [xmm7360/xmm7360-pci#203] opened 2023-03-29 07:21 UTC
Is there any way to set credentials for the APN?

_In my case the username contains a backslash character. So even if supplying credentials was possible it still might be a challenge..._

Unfortunately,
`AT+CGAUTH`
seems not to be supported (CME ERROR: 4). 

`AT+XGAUTH=1,1,"user","pass"`
results in "CME ERROR: 50"

**Comment by yummy527** [comment] 2023-04-07 16:07
[Here](https://forums.quectel.com/t/the-right-way-to-apn-setting/12117) mentions password and user.

**Comment by elronzo** [comment] 2023-05-25 12:09
No luck trying AT+QICSGP

**Comment by tgxn** [comment] 2023-07-17 08:57
Dupe of https://github.com/xmm7360/xmm7360-pci/issues/62 still happy for someone to work it out, but not something I'm in a position to look at.

**Closed by tgxn** 2023-07-17 08:57 UTC
